baseURL = 'https://arijoshi.github.io/'
languageCode = 'en-gb'
title = 'ari joshi'
theme = 'typo'

# Google analytics code
googleAnalytics = "G-xxxxxxxxx"

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "personal website"
showFooter = false
faviconPath = '/img'

#[params]
#howFooter = false
#footerContent = ""

#[params]
#faviconPath = '/static'



# Appearance settings
theme = 'dark'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = ''
homeIntroContent = """
 


I am a PhD student in semantics & pragmatics based at [ZAS Berlin](https://www.leibniz-zas.de/en/). I'm interested in phenomena surrounding context shift, quotativity, indexicals, not-at-issue meaning, negation, and degrees. I use mainly formal and experimental methods, and try to computate sometimes.

#### contact

[***email***] joshi [at] leibniz [hyphen] zas [dot] de  

[***address***] Leibniz Zentrum Allgemeine Sprachwissenschaft, Pariser Str. 1, 10719 Berlin 

#### name 

I go by and write as *Ari*, which is my nickname.<br>My legal name, which I do not use outside of official documents, is *Aarati Joshi*, pronounced [​​a​​ɾt̪​​i​ ​d͡z​​o​​ɕ​i​​] (often germanised to [jo​​ʃ​i]). (And in some places you may find *Aarti*, which is closer to how it is pronounced than the legal spelling...)

"""

# Collection to display on home
#homeCollectionTitle = 'Posts'
#homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = false
listDateFormat = '2 Jan 2006'

# Breadcrumbs
[params.breadcrumbs]
enabled = false 
#showCurrentPage = false
#home = "~"

# Social icons
[[params.social]]
name = "orcid"
url = "https://orcid.org/0000-0002-6876-394X"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/ari-j-870a5b1b5/"

[[params.social]]
name = "bluesky"
url = "https://bsky.app/profile/arijoshi.bsky.social"

[[params.social]]
name = "lastdotfm"
url = "https://www.last.fm/user/ari_j"

#[[params.social]]
#name = "github"
#url = "https://github.com/user"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "about"
url = "/about"

[[params.menu]]
name = "output"
url = "/output"

[[params.menu]]
name = "cv"
url = "/public.pdf"
newTab = true

[[params.menu]]
name = "random"
url = "/random"

#[[params.menu]]
#name = "blog"
#url = "/blog"


# Syntax highlight on code blocks
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"

[caches]
  [caches.images]
    dir = ':cacheDir/images'