baseURL = 'https://arijoshi.github.io/'
languageCode = 'en-gb'
title = 'aarti (ari) joshi'
theme = 'typo'

# Google analytics code
googleAnalytics = "G-xxxxxxxxx"

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "personal website"
showFooter = false
faviconPath = '/img'

#[params]
#howFooter = false
#footerContent = ""

#[params]
#faviconPath = '/static'

# Appearance settings
theme = 'light'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'contact'
homeIntroContent = """
 
[***email***] joshi [at] leibniz [hyphen] zas [dot] de  

[***address***] Leibniz Zentrum Allgemeine Sprachwissenschaft, Pariser Str. 1, 10719 Berlin 

## about 

[***profile***] I am a PhD student based at ZAS Berlin. I like thinking about meaning and how we coordinate on it, within and beyond what is explicitly uttered. My interests lie across & between semantics and pragmatics--I'm especially captivated by phenomena concerning degrees, not-at-issue meaning, and negation. I use mainly formal and experimental methods, and try to computate sometimes.

[***projects***] In my doctoral project, I am looking at the cancellation/denial of inferences under negation. This work is supervised by Uli Sauerland here at ZAS and Michael Franke over at Tübingen. 
At ZAS, I am part of the LMBayes project which focuses on developing probabilistic models of meaning. I also enjoy puzzling over the "depth-charge" illusion, which was the topic of my MSc thesis and continues to be a source of delight.

[***background***] I completed my masters at the University of Potsdam, focusing mainly on semantics and psycholinguistics. While studying, I also worked as an RA both at ZAS (first with Aron Hirsch, later with Andreea C. Nicolae) and at the university (first in Gisbert Fanselow's project on word order, and then in Malte Zimmermann's group). Before coming to linguistics proper, I studied languages & literature as well as applied linguistics. 

[***hobbies***] Outside of work, most of my thoughts are probably about cats. Check mine out {here}. I amuse myself with the usual homebody stuff: books (fiction!), puzzles, board games, and a ton of music. Recommendations are always welcome!

[***name***]I go by *ari*, my nickname. But on paper I use *Aarti Joshi*, pronounced [​​a​​ɾt̪​​i​ ​d͡z​​o​​ɕ​i​​] (often germanised to [jo​​ʃ​i]...)

"""

# Collection to display on home
#homeCollectionTitle = 'Posts'
#homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
[params.breadcrumbs]
enabled = false
#showCurrentPage = true
#home = "Home"

# Social icons
[[params.social]]
name = "orcid"
url = "https://orcid.org/0000-0002-6876-394X"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/ari-j-870a5b1b5/"

#[[params.social]]
#name = "github"
#url = "https://github.com/user"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "output"
url = "/output"

#[[params.menu]]
#name = "cv"
#url = "/cv"

[[params.menu]]
name = "random"
url = "/random"


# Syntax highlight on code blocks
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"

[caches]
  [caches.images]
    dir = ':cacheDir/images'